// Public component selectors. Keep behavior hooks and page layout classes intact.
const shared = (key, label, selector) => ({ key: `shared-${key}`, label, selector, group: "کامپوننت‌های مشترک" });
export const COMPONENT_TARGETS = [
    shared("header-auth", "هدر · دکمه ورود", ".site-header__auth"),
    shared("header-language", "هدر · انتخاب زبان", ".site-language"),
    shared("menu-toggle", "هدر · دکمه منوی موبایل", "[data-menu-open]"),
    shared("mobile-links", "منوی موبایل · لینک‌ها", ".mobile-menu a"),
    shared("footer-logo", "فوتر · لوگو", ".site-footer__logo"),
    shared("footer-description", "فوتر · توضیحات", ".site-footer__description"),
    shared("footer-navigation", "فوتر · لینک‌های منو", ".site-footer__navigation a"),
    shared("footer-contact", "فوتر · اطلاعات تماس", ".site-footer__contact"),
    shared("footer-bottom", "فوتر · نوار پایین", ".site-footer__bottom"),
    shared("footer-back-top", "فوتر · بازگشت به بالا", ".site-footer__back-top"),
    shared("product-card", "کارت محصول · قاب", ".product-card"),
    shared("product-card-body", "کارت محصول · محتوا", ".product-card__body"),
    shared("card-media-tag", "کارت‌ها · تگ روی تصویر", ".site-card__media-tag"),
    shared("card-meta-tag", "کارت‌ها · تگ مشخصات پایین", ".site-card__meta-tag"),
    shared("card-meta-row", "کارت‌ها · ردیف مشخصات پایین", ".site-card__meta-row"),
    shared("card-cta", "کارت‌ها · لینک و دکمه", ".site-card__cta"),
    shared("consultation-copy", "مشاوره · محتوا", ":is(.site-consultation__content, .catalog-consultation__content)"),
    shared("consultation-title", "مشاوره · عنوان", ":is(.site-consultation h2, .catalog-consultation__title)"),
    shared("consultation-text", "مشاوره · توضیحات", ":is(.site-consultation p, .catalog-consultation__description)"),
    shared("consultation-fields", "مشاوره · فیلدها", ":is(.site-consultation input, .catalog-consultation__field)"),
    shared(
        "consultation-submit",
        "مشاوره · دکمه ارسال",
        ":is(.site-consultation button[type=submit], .catalog-consultation__submit)",
    ),
    shared("consultation-visual", "مشاوره · تصویر", ".catalog-consultation__visual"),
    shared("faq-title", "پرسش‌ها · عنوان", ".site-faq > h2"),
    shared("faq-question", "پرسش‌ها · دکمه سؤال", ".site-faq__question"),
    shared("faq-answer", "پرسش‌ها · پاسخ", ".site-faq__answer"),
    shared("testimonials", "دیدگاه‌ها · بخش", ".site-testimonials"),
    shared("testimonial-card", "دیدگاه‌ها · کارت", ".site-testimonial"),
    shared("testimonial-text", "دیدگاه‌ها · متن", ".site-testimonial .site-card__description"),
    shared("testimonial-name", "دیدگاه‌ها · نام", ".site-testimonial .site-card__title"),
    shared("partners", "مشتریان · بخش لوگوها", ".home-partners"),
    shared("partner-logo", "مشتریان · لوگو", ".home-partners__item img"),
    shared("search-form", "جست‌وجو · قاب فرم", ".product-search"),
    shared("search-fields", "جست‌وجو · فیلدها", ":is(.product-search__input, .product-search select)"),
    shared("search-submit", "جست‌وجو · دکمه", ".product-search__submit"),
    shared("filter-chip", "جست‌وجو · تگ فیلتر", ".filter-chip"),
    shared("auth-dialog", "ورود و عضویت · پنجره", ".auth-card"),
    shared("auth-title", "ورود و عضویت · عنوان", ".auth-title"),
    shared("auth-fields", "ورود و عضویت · فیلدها", ".auth-input"),
    shared("technical-card", "جدول فنی · قاب", ".details-card"),
    shared("technical-cell", "جدول فنی · سلول‌ها", ".details-table td"),
    shared("technical-heading", "جدول فنی · عنوان ستون", ".details-table th"),
];
