// Shared by the editor and the Vite writeback endpoint. No browser/Node APIs here.
import { normalizePatterns } from "./pattern-model.js";
import { BREAKPOINTS, PAGE_NAMES, TARGETS, PROPERTIES, STATES } from "./schema.js";
import { normalizeProperty, rangeQuery } from "./values.js";
import { LEGACY_TOKEN_NAMES, TAG_TARGETS, migrateLegacyRules } from "./compatibility.js";
import { TOKEN_CONTRACTS, normalizeTokenValue, tokenSelectors } from "./token-values.js";
export { BREAKPOINTS, PAGE_NAMES, TARGETS, PROPERTIES, STATES } from "./schema.js";

export function emptyConfig() {
    return { version: 1, rules: [] };
}

export function defaultConfig() {
    const rules = [];
    const add = (key, properties, breakpoint = "all", page = "*") =>
        rules.push({ page, breakpoint, target: { kind: "role", key }, properties });
    for (const key of [
        "hero-eyebrow",
        "hero-title",
        "section-title",
        "card-title",
        "card-cta",
        ...TAG_TARGETS,
        "footer-title",
    ])
        add(key, { "text-align": "right", direction: "rtl", ...(key === "card-meta-tag" ? { "padding-top": 8 } : {}) });
    for (const key of ["body-text", "hero-description", "card-description"])
        add(key, {
            "text-align": "justify",
            "text-align-last": "right",
            direction: "rtl",
            ...(key === "card-description" ? { "description-lines": 2 } : {}),
        });
    for (const breakpoint of ["desktop", "tablet", "mobile"]) {
        add("card-title", { "font-size": breakpoint === "mobile" ? 20 : 17 }, breakpoint);
        add("card-description", { "font-size": breakpoint === "mobile" ? 18 : 14 }, breakpoint);
    }
    add("card-cta", { "font-size": 12 }, "desktop");
    for (const key of TAG_TARGETS) add(key, { "font-size": 10 }, "mobile");
    add("card-title", { "font-size": 16 }, "compact", "expertise");
    add("card-description", { "font-size": 14 }, "compact", "expertise");
    for (const [page, key, size] of [
        ["product-details", "product-summary-title", 17],
        ["product-details", "product-summary-description", 14],
        ["project-details", "project-product-title", 16],
        ["project-details", "project-product-description", 14],
    ])
        add(key, { "font-size": size }, "mobile", page);
    add("product-summary-description", { "description-lines": 0 }, "all", "product-details");
    return normalizeConfig({ version: 1, rules });
}

// Element selectors are generated by the picker: identifiers and structural
// children only. No arbitrary CSS, URLs, imports, attribute payloads or escapes.
export function validElementSelector(selector) {
    if (typeof selector !== "string" || !selector || selector.length > 2000) return false;
    const parts = selector.split(" > ");
    if (parts.length > 32) return false;
    return parts.every(
        (part) =>
            /^(?:[a-z][a-z0-9-]*)?(?:#[A-Za-z_][\w-]*|(?:\.[A-Za-z_][\w-]*){0,3})(?::nth-of-type\([1-9]\d{0,4}\))?$/.test(
                part,
            ) && part.length > 0,
    );
}

export function normalizeConfig(input) {
    if (!input || input.version !== 1 || !Array.isArray(input.rules) || input.rules.length > 1000)
        throw new Error("فایل تنظیمات معتبر نیست.");
    const seen = new Set();
    const rules = migrateLegacyRules(input.rules)
        .map((source) => {
            if (!source || !["*", ...Object.keys(PAGE_NAMES)].includes(source.page))
                throw new Error("صفحه نامعتبر است.");
            if (!BREAKPOINTS.some((item) => item.key === source.breakpoint)) throw new Error("اندازه نامعتبر است.");
            const target = source.target;
            let cleanTarget;
            if (target?.kind === "token") {
                if (
                    !Object.hasOwn(TOKEN_CONTRACTS, target.key) ||
                    !TOKEN_CONTRACTS[target.key].editable ||
                    Object.keys(source.properties || {}).some((name) => name !== target.key) ||
                    (source.state && source.state !== "normal")
                )
                    throw new Error("انتخاب متغیر معتبر نیست.");
                cleanTarget = { kind: "token", key: target.key };
            } else if (target?.kind === "role") {
                const role = TARGETS.find((item) => item.key === target.key);
                if (!role || (role.pages && !role.pages.includes(source.page))) throw new Error("بخش نامعتبر است.");
                cleanTarget = { kind: "role", key: role.key };
            } else if (
                ["element", "component"].includes(target?.kind) &&
                (source.page !== "*" || target.kind === "component") &&
                validElementSelector(target.selector) &&
                (target.kind !== "component" || !target.selector.includes("#"))
            ) {
                cleanTarget = {
                    kind: target.kind,
                    selector: target.selector,
                    label: String(target.label || "بخش انتخاب‌شده").slice(0, 120),
                };
            } else throw new Error("انتخاب بخش معتبر نیست.");
            if (!source.properties || Array.isArray(source.properties) || typeof source.properties !== "object")
                throw new Error("مقادیر استایل معتبر نیستند.");
            const properties = {};
            for (const [name, value] of Object.entries(source.properties)) {
                const canonical = LEGACY_TOKEN_NAMES[name] || name;
                if (
                    PROPERTIES[canonical]?.target === "header-behavior" &&
                    cleanTarget.kind !== "token" &&
                    (cleanTarget.kind !== "role" ||
                        cleanTarget.key !== "header-behavior" ||
                        (source.state && source.state !== "normal"))
                )
                    throw new Error("تنظیم منوی ثابت را از بخش منوی بالای صفحه و حالت معمولی ویرایش کن.");
                properties[canonical] =
                    cleanTarget.kind === "token"
                        ? normalizeTokenValue(canonical, value)
                        : normalizeProperty(canonical, value);
            }
            if (
                "image-source" in properties &&
                (source.page !== "about" ||
                    cleanTarget.kind !== "role" ||
                    cleanTarget.key !== "about-image" ||
                    (source.state && source.state !== "normal"))
            )
                throw new Error("تغییر فایل تصویر فقط برای تصویر اصلی درباره ما و حالت معمولی مجاز است.");
            const rule = { page: source.page, breakpoint: source.breakpoint, target: cleanTarget, properties };
            if (source.state !== undefined && !STATES.some((item) => item.key === source.state))
                throw new Error("حالت المان معتبر نیست.");
            if (source.state && source.state !== "normal") rule.state = source.state;
            if (source.enabled !== undefined && typeof source.enabled !== "boolean")
                throw new Error("فعال بودن قانون معتبر نیست.");
            if (source.enabled === false) rule.enabled = false;
            if (rule.breakpoint === "range") {
                const range = source.range;
                if (
                    !range ||
                    !Number.isInteger(range.min) ||
                    range.min < 0 ||
                    range.min > 7680 ||
                    (range.max !== null &&
                        (!Number.isInteger(range.max) || range.max > 7680 || range.max < 0 || range.min > range.max))
                )
                    throw new Error("بازهٔ عرض معتبر نیست.");
                rule.range = { min: range.min, max: range.max };
            }
            const key = ruleKey(rule);
            if (seen.has(key)) throw new Error("تنظیم تکراری برای یک بخش وجود دارد.");
            seen.add(key);
            return rule;
        })
        .filter((rule) => Object.keys(rule.properties).length);
    if (rules.length > 1000) throw new Error("تعداد قانون‌ها بیش از حد مجاز است.");
    return { version: 1, rules, ...(input.patterns ? { patterns: normalizePatterns(input.patterns) } : {}) };
}

export function ruleKey(rule) {
    return [
        rule.page,
        rule.breakpoint,
        rule.range ? `${rule.range.min}-${rule.range.max}` : "",
        rule.target.kind,
        rule.target.key || rule.target.selector,
        ...(rule.state ? [rule.state] : []),
    ].join("|");
}

export function targetSelector(target) {
    if (target.kind === "token") return tokenSelectors(target.key);
    return target.kind === "role" ? TARGETS.find((item) => item.key === target.key)?.selector : target.selector;
}

export function propertyCSS(name, value) {
    if (name === "grid-template-columns" && typeof value === "number") return `repeat(${value}, minmax(0, 1fr))`;
    const spec = PROPERTIES[name];
    return typeof value === "number" ? `${value}${spec?.unit ?? ""}` : value;
}

export function compileCSS(input, { previewState } = {}) {
    const config = normalizeConfig(input);
    const priority = (rule) =>
        (rule.target.kind === "token"
            ? 500
            : rule.target.kind === "element"
              ? 400
              : rule.target.kind === "component"
                ? rule.page === "*"
                    ? 200
                    : 300
                : rule.page === "*"
                  ? 0
                  : 100) +
        (rule.target.kind === "role" ? TARGETS.findIndex((item) => item.key === rule.target.key) : 0);
    const ordered = config.rules
        .filter((rule) => rule.enabled !== false)
        .sort(
            (a, b) =>
                priority(a) - priority(b) ||
                BREAKPOINTS.findIndex((item) => item.key === a.breakpoint) -
                    BREAKPOINTS.findIndex((item) => item.key === b.breakpoint),
        );
    let css =
        "/* Marpich template styles. Generated by tools/customizer.html.\n * Edit with the customizer or src/data/customizer/settings.json. */\n";
    for (const rule of ordered) {
        const body = rule.page === "*" ? "body[data-page]" : `body[data-page="${rule.page}"]`;
        if (rule.target.kind === "token") {
            const selector = tokenSelectors(rule.target.key, body);
            const declarations = Object.entries(rule.properties).map(
                ([name, value]) => `    ${name}: ${value} !important;`,
            );
            let block = `${selector} {\n${declarations.join("\n")}\n}\n`;
            const query = rule.range
                ? rangeQuery(rule.range)
                : BREAKPOINTS.find((item) => item.key === rule.breakpoint).query;
            if (query) block = `@media ${query} {\n${block}}\n`;
            css += block;
            continue;
        }
        const child = targetSelector(rule.target);
        const state = STATES.find((item) => item.key === (rule.state || "normal"));
        const suffix =
            previewState === state.key && state.key !== "normal"
                ? `:is(${state.suffix}, .mps-preview-state)`
                : state.suffix;
        const selector = `${body}${child ? ` ${child}` : ""}${suffix}${"description-lines" in rule.properties ? ":not([hidden])" : ""}`;
        const declarations = Object.entries(rule.properties)
            .filter(([name]) => name !== "description-lines" && !PROPERTIES[name]?.virtual)
            .map(([name, value]) => `    ${name}: ${propertyCSS(name, value)} !important;`);
        const role = rule.target.kind === "role" ? rule.target.key : "";
        // Keep home's inner canvas in sync without overriding an explicit height.
        if (role === "hero" || /^#hero-[\w-]+$/.test(child)) {
            const minimum = rule.properties["min-height"];
            const height = rule.properties.height;
            if (minimum !== undefined)
                declarations.push(`    --hero-min-height: ${propertyCSS("min-height", minimum)} !important;`);
            else if (height !== undefined && height !== "auto")
                declarations.push(
                    `    --hero-min-height: ${propertyCSS("height", height)} !important;`,
                    "    min-height: 0 !important;",
                );
            if (minimum !== undefined && height === undefined) declarations.push("    height: auto !important;");
        }
        if (role === "card-description" && ("font-size" in rule.properties || "line-height" in rule.properties))
            declarations.push("    max-height: none !important;");
        const lines = rule.properties["description-lines"];
        if (lines !== undefined) {
            declarations.push(
                ...(!("display" in rule.properties)
                    ? [`    display: ${lines ? "-webkit-box" : "block"} !important;`]
                    : []),
                "    -webkit-box-orient: vertical !important;",
                `    -webkit-line-clamp: ${lines || "unset"} !important;`,
                `    line-clamp: ${lines || "none"} !important;`,
                "    max-height: none !important;",
                "    height: auto !important;",
                "    min-height: 0 !important;",
                `    overflow: ${lines ? "hidden" : "visible"} !important;`,
            );
        }
        if (rule.properties["text-align"] === "justify" && !("text-align-last" in rule.properties))
            declarations.push("    text-align-last: right !important;", "    text-justify: inter-word !important;");
        if ("translate-x" in rule.properties || "translate-y" in rule.properties)
            declarations.push(
                `    translate: ${propertyCSS("translate-x", rule.properties["translate-x"] ?? 0)} ${propertyCSS("translate-y", rule.properties["translate-y"] ?? 0)} !important;`,
            );
        if (!declarations.length) continue;
        let block = `${selector} {\n${declarations.join("\n")}\n}\n`;
        // The active header row owns the visible height. Hidden device rows keep
        // their display rules, while page/range/state scoping matches the root.
        if (["header", "shared-header"].includes(role) || child === ".site-header") {
            const sizes = ["height", "min-height", "max-height"].filter((name) => name in rule.properties);
            if (sizes.length)
                block += `${selector} :is(.site-header__desktop, .site-header__mobile) {\n${sizes.map((name) => `    ${name}: ${propertyCSS(name, rule.properties[name])} !important;`).join("\n")}\n}\n`;
        }
        const query = rule.range
            ? rangeQuery(rule.range)
            : BREAKPOINTS.find((item) => item.key === rule.breakpoint).query;
        if (query) block = `@media ${query} {\n${block}}\n`;
        css += block;
    }
    return css;
}

// Source settings deliberately omit artwork copies; archive contains separate JSONs.
export function persistedSettings(input) {
    const { patterns, ...settings } = normalizeConfig(input);
    return settings;
}

export function ruleAppliesAtWidth(rule, width) {
    if (rule.enabled === false) return false;
    if (rule.range) return width >= rule.range.min && (rule.range.max === null || width <= rule.range.max);
    return (
        rule.breakpoint === "all" ||
        (rule.breakpoint === "desktop" && width >= 1180) ||
        (rule.breakpoint === "tablet" && width >= 640 && width <= 1179) ||
        (rule.breakpoint === "mobile" && width <= 639) ||
        (rule.breakpoint === "compact" && width <= 450)
    );
}
