// Pure public contract: targets, responsive ranges and editable CSS properties.
import { COMPONENT_TARGETS } from "./components.js";
export const BREAKPOINTS = [
    { key: "all", label: "همه اندازه‌ها", query: "" },
    { key: "desktop", label: "دسکتاپ · ۱۱۸۰ به بالا", query: "(min-width: 1180px)" },
    { key: "tablet", label: "تبلت · ۶۴۰ تا ۱۱۷۹", query: "(min-width: 640px) and (max-width: 1179px)" },
    { key: "mobile", label: "موبایل · تا ۶۳۹", query: "(max-width: 639px)" },
    { key: "compact", label: "موبایل کوچک · تا ۴۵۰", query: "(max-width: 450px)" },
    { key: "range", label: "بازهٔ دلخواه · min / max", query: "" },
];

export const PAGE_NAMES = {
    home: "صفحه اصلی",
    products: "محصولات",
    "product-details": "جزئیات محصول",
    contact: "تماس با ما",
    "project-details": "جزئیات پروژه",
    about: "درباره ما",
    projects: "پروژه‌ها",
    "industry-textile": "صنعت نساجی",
    expertise: "حوزه تخصصی",
    "air-handling": "هواساز",
    industries: "صنایع",
    articles: "مقالات",
};

export const TARGETS = [
    { key: "page", label: "کل صفحه", selector: "", group: "چیدمان" },
    { key: "header-behavior", label: "منوی بالای صفحه · ثابت‌شدن با اسکرول", selector: ".site-header", group: "هدر" },
    { key: "header", label: "هدر این صفحه · اندازه و ارتفاع", selector: ".site-header", group: "هدر" },
    {
        key: "header-content",
        label: "هدر این صفحه · چیدمان و فاصله",
        selector: ":is(.site-header__desktop, .site-header__mobile)",
        group: "هدر",
    },
    { key: "hero", label: "هیرو · ارتفاع", selector: ".site-hero", group: "هیرو" },
    { key: "hero-content", label: "هیرو · فاصله متن از بالا", selector: ".site-hero__content", group: "هیرو" },
    { key: "hero-eyebrow", label: "هیرو · عنوان کوچک / مسیر صفحه", selector: ".site-hero__eyebrow", group: "هیرو" },
    { key: "hero-title", label: "هیرو · عنوان اصلی", selector: ".site-hero__title", group: "هیرو" },
    { key: "hero-description", label: "هیرو · توضیحات", selector: ".site-hero__description", group: "هیرو" },
    { key: "section", label: "بخش‌های محتوا · فاصله و ارتفاع", selector: "main section", group: "محتوا" },
    {
        key: "section-title",
        label: "عنوان بخش‌ها",
        selector:
            "main h2:not(.featured-card__title):not(.site-card__title):not(.project-details__testimonial-title):not(:where(.project-details__reference-heading))",
        group: "محتوا",
    },
    {
        key: "body-text",
        label: "متن‌ها و توضیحات کامل",
        selector:
            ":is(main p, main li, .site-prose):not(.featured-card__description):not(.site-card__description):not(.site-hero__description):not(.site-hero__eyebrow):not(.site-card__media-tag):not(.site-card__meta-tag):not(.site-card__status-tag):not(.project-details__testimonial-kicker-copy):not(:where(.project-details__reference-copy))",
        group: "محتوا",
    },
    { key: "card", label: "همه باکس‌ها · ارتفاع و فاصله", selector: ".site-card", group: "باکس‌ها" },
    { key: "card-title", label: "عنوان باکس‌ها", selector: ".site-card__title", group: "باکس‌ها" },
    { key: "card-description", label: "توضیحات باکس‌ها", selector: ".site-card__description", group: "باکس‌ها" },
    { key: "card-cta", label: "CTA باکس‌ها", selector: ".site-card__cta", group: "باکس‌ها" },
    { key: "card-media-tag", label: "تگ روی تصویر", selector: ".site-card__media-tag", group: "باکس‌ها" },
    { key: "card-meta-tag", label: "تگ مشخصات زیر متن", selector: ".site-card__meta-tag", group: "باکس‌ها" },
    { key: "card-status-tag", label: "برچسب وضعیت محصول", selector: ".site-card__status-tag", group: "باکس‌ها" },
    { key: "search", label: "فرم جست‌وجو", selector: ":is(.product-search, .articles-search)", group: "فرم‌ها" },
    { key: "filter-chips", label: "فیلترهای انتخاب‌شده", selector: ".product-search__bottom", group: "فرم‌ها" },
    {
        key: "fields",
        label: "فیلدهای فرم",
        selector: ":is(input:not([type=checkbox]):not([type=radio]):not([type=file]), select, textarea)",
        group: "فرم‌ها",
    },
    {
        key: "project-meta",
        label: "اطلاعات پروژه · باکس‌ها",
        selector: ".project-details__meta-item",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-meta-grid",
        label: "اطلاعات پروژه · ستون‌ها و فاصله",
        selector: ".project-details__meta-grid",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-meta-label",
        label: "اطلاعات پروژه · عنوان",
        selector: ".project-details__meta-item > span",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-meta-value",
        label: "اطلاعات پروژه · مقدار",
        selector: ".project-details__meta-item > strong",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-stat",
        label: "دستاوردهای پروژه · باکس",
        selector: ".project-details__stat",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-stats-grid",
        label: "دستاوردهای پروژه · ستون‌ها و فاصله",
        selector: ".project-details__stats-grid",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-stat-icon",
        label: "دستاوردهای پروژه · آیکون",
        selector: ".project-details__stat-icon",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-reference-heading",
        label: "عنوان بخش‌های بازگردانی‌شده",
        selector: ".project-details__reference-heading",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-technical-note",
        label: "توضیح پایین جدول پروژه",
        selector: ".project-details__technical .details-card__note p",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-testimonial",
        label: "دیدگاه کارفرما · متن کامل",
        selector: ".project-details__testimonial-body",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-summary",
        label: "تصویر و اطلاعات پروژه",
        selector: ".project-details__summary",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "product-summary",
        label: "باکس اصلی محصول",
        selector: ".product-details__summary",
        pages: ["product-details"],
        group: "جزئیات محصول",
    },
    {
        key: "product-summary-title",
        label: "عنوان اصلی محصول",
        selector: "#product-title",
        pages: ["product-details"],
        group: "جزئیات محصول",
    },
    {
        key: "product-summary-description",
        label: "توضیح اصلی محصول",
        selector: ".product-details__summary .site-card__description",
        pages: ["product-details"],
        group: "جزئیات محصول",
    },
    {
        key: "product-quick-spec-tag",
        label: "جزئیات محصول · تگ مشخصات زیر متن",
        selector: ".product-details__meta-tag",
        pages: ["product-details"],
        group: "جزئیات محصول",
    },
    {
        key: "project-product-meta-tag",
        label: "محصولات پروژه · تگ زیر متن",
        selector: ".project-details__product-meta-tag",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-product-media-tag",
        label: "محصولات پروژه · تگ روی تصویر",
        selector: ".project-details__product-media-tag",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-product-title",
        label: "محصولات پروژه · عنوان",
        selector: ".project-details__product-card .site-card__title",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-product-description",
        label: "محصولات پروژه · توضیح",
        selector: ".project-details__product-card .site-card__description",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-stat-title",
        label: "دستاوردها · عنوان",
        selector: ".project-details__stat > h3",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "project-stat-description",
        label: "دستاوردها · توضیح",
        selector: ".project-details__stat > p",
        pages: ["project-details"],
        group: "جزئیات پروژه",
    },
    {
        key: "products-featured-grid",
        label: "محصولات منتخب · چیدمان گرید",
        selector: ".featured-products",
        pages: ["products"],
        group: "محصولات منتخب",
    },
    {
        key: "products-featured-card",
        label: "محصولات منتخب · قاب کارت‌ها",
        selector: ".featured-card",
        pages: ["products"],
        group: "محصولات منتخب",
    },
    {
        key: "products-featured-title",
        label: "محصولات منتخب · عنوان کارت‌ها",
        selector: ".featured-card__title",
        pages: ["products"],
        group: "محصولات منتخب",
    },
    {
        key: "products-featured-description",
        label: "محصولات منتخب · توضیح کارت‌ها",
        selector: ".featured-card__description",
        pages: ["products"],
        group: "محصولات منتخب",
    },
    {
        key: "products-featured-count",
        label: "محصولات منتخب · تعداد محصولات",
        selector: ".featured-card__count",
        pages: ["products"],
        group: "محصولات منتخب",
    },
    {
        key: "products-featured-image",
        label: "محصولات منتخب · تصاویر کارت‌ها",
        selector: ".featured-card__image",
        pages: ["products"],
        group: "محصولات منتخب",
    },
    { key: "technical-card", label: "قاب جدول فنی", selector: ".details-card", group: "جدول فنی" },
    { key: "technical-cell", label: "سلول‌های جدول", selector: ".details-table td", group: "جدول فنی" },
    { key: "technical-heading", label: "عنوان ستون‌های جدول", selector: ".details-table th", group: "جدول فنی" },
    { key: "technical-image", label: "تصویر فنی", selector: ".details-visual img", group: "جدول فنی" },
    {
        key: "about-image-container",
        label: "تصویر درباره ما · عرض و فاصله از هدر",
        selector: ".about-team-wrap",
        pages: ["about"],
        group: "درباره ما",
    },
    {
        key: "about-image-frame",
        label: "تصویر درباره ما · قاب، ارتفاع و گوشه‌ها",
        selector: ".about-team-media",
        pages: ["about"],
        group: "درباره ما",
    },
    {
        key: "about-image",
        label: "تصویر اصلی درباره ما · فایل، اندازه و برش",
        selector: ".about-team-media__image",
        pages: ["about"],
        group: "درباره ما",
    },
    {
        key: "expertise-image",
        label: "تصاویر حوزه تخصصی",
        selector: ".expertise-page__media-image",
        pages: ["expertise"],
        group: "حوزه تخصصی",
    },
    { key: "footer", label: "فوتر · ارتفاع و فاصله", selector: ".site-footer", group: "فوتر" },
    {
        key: "footer-pattern",
        label: "پترن فوتر · وضوح و اندازه",
        selector: ".site-footer .site-pattern-graphic",
        group: "فوتر",
    },
    { key: "footer-title", label: "عنوان‌های فوتر", selector: ".site-footer h3", group: "فوتر" },
    {
        key: "footer-text",
        label: "متن‌ها و لینک‌های فوتر",
        selector: ".site-footer :is(p, li, a):not(.site-footer__back-top)",
        group: "فوتر",
    },

    // Stable component hooks; page-specific classes stay behind these public roles.
    { key: "shared-header", label: "هدر مشترک", selector: ".site-header", group: "کامپوننت‌های مشترک" },
    {
        key: "shared-header-desktop",
        label: "هدر · چیدمان دسکتاپ",
        selector: ".site-header__desktop",
        group: "کامپوننت‌های مشترک",
    },
    {
        key: "shared-header-mobile",
        label: "هدر · چیدمان موبایل",
        selector: ".site-header__mobile",
        group: "کامپوننت‌های مشترک",
    },
    { key: "shared-logo", label: "لوگوی هدر", selector: ".site-header__logo", group: "کامپوننت‌های مشترک" },
    {
        key: "shared-navigation",
        label: "لینک‌های منوی دسکتاپ",
        selector: ".site-nav-link",
        group: "کامپوننت‌های مشترک",
    },
    { key: "shared-dropdown", label: "زیرمنوهای دسکتاپ", selector: ".site-nav-dropdown", group: "کامپوننت‌های مشترک" },
    { key: "shared-mobile-menu", label: "منوی موبایل", selector: ".mobile-menu", group: "کامپوننت‌های مشترک" },
    {
        key: "shared-footer-layout",
        label: "ستون‌های فوتر",
        selector: ".site-footer__layout",
        group: "کامپوننت‌های مشترک",
    },
    {
        key: "shared-footer-social",
        label: "شبکه‌های اجتماعی فوتر",
        selector: ".site-footer__socials",
        group: "کامپوننت‌های مشترک",
    },
    {
        key: "shared-consultation",
        label: "بخش مشاوره",
        selector: ":is([data-consultation], .catalog-consultation)",
        group: "کامپوننت‌های مشترک",
    },
    {
        key: "shared-consultation-form",
        label: "فرم‌های مشاوره",
        selector: ":is([data-consultation] form, .catalog-consultation__form)",
        group: "کامپوننت‌های مشترک",
    },
    { key: "shared-faq", label: "بخش پرسش‌های متداول", selector: ".site-faq", group: "کامپوننت‌های مشترک" },
    {
        key: "shared-faq-item",
        label: "آیتم پرسش‌های متداول",
        selector: ".site-faq__item",
        group: "کامپوننت‌های مشترک",
    },
    {
        key: "shared-card-media",
        label: "قاب تصاویر کارت‌ها",
        selector: ".site-card__media",
        group: "کامپوننت‌های مشترک",
    },
    { key: "shared-card-image", label: "تصاویر کارت‌ها", selector: ".site-card__image", group: "کامپوننت‌های مشترک" },
    { key: "shared-card-body", label: "محتوای کارت‌ها", selector: ".site-card__body", group: "کامپوننت‌های مشترک" },
    { key: "shared-grid", label: "Grid کارت‌ها", selector: ".site-card-grid", group: "کامپوننت‌های مشترک" },
    ...COMPONENT_TARGETS,
    { key: "theme", label: "توکن‌های طراحی · رنگ و فاصله", selector: "", group: "تنظیمات سراسری" },
];

export const STATES = [
    { key: "normal", label: "عادی", suffix: "" },
    { key: "hover", label: "Hover", suffix: ":hover" },
    { key: "focus", label: "Focus", suffix: ":focus" },
    { key: "focus-visible", label: "Focus با کیبورد", suffix: ":focus-visible" },
    { key: "active", label: "هنگام کلیک", suffix: ":active" },
];
export const VIEWPORT_LIMITS = { min: 240, max: 7680 };

const number = (min, max, unit = "px", extra = []) => ({
    type: "number",
    min,
    max,
    unit,
    extra,
    ...(unit === "px" || unit === "%"
        ? {
              units: [
                  unit,
                  ...["px", "rem", "em", "%", "vw", "vh", "dvh", "svh", "lvh", "vmin", "vmax"].filter(
                      (item) => item !== unit,
                  ),
              ],
          }
        : {}),
});
const choice = (...values) => ({ type: "choice", values });
export const PROPERTIES = {
    "--header-fixed-enabled": {
        ...choice("1", "0"),
        target: "header-behavior",
        help: "فعال: منو پس از آستانهٔ اسکرول بالای صفحه می‌ماند. غیرفعال: هدر اصلی همراه صفحه حرکت می‌کند.",
    },
    "--header-fixed-scroll-threshold": {
        ...number(0, 7680),
        target: "header-behavior",
        help: "مقدار اسکرول عمودی برای ثابت‌شدن منو، برحسب پیکسل. مقدار ۰ منو را از ابتدای صفحه ثابت می‌کند.",
    },
    "--header-fixed-top": {
        ...number(0, 400),
        target: "header-behavior",
        help: "فاصلهٔ منوی ثابت از بالا در حالت دسکتاپ؛ برای صفحه یا بازه مستقل تنظیم کن. در حالت همبرگری (کمتر از ۱۱۸۰px)، فاصله و فضای بالای ردیف خودکار صفر می‌شوند.",
    },
    "--header-fixed-background-color": {
        type: "color",
        target: "header-behavior",
        help: "رنگ زمینه فقط زمانی که منو ثابت شده است. رنگ تیره، خوانایی لینک‌های سفید را حفظ می‌کند.",
    },
    "--header-fixed-background-opacity": {
        ...number(0, 100, ""),
        target: "header-behavior",
        help: "درصد پوشانندگی زمینه: ۰ شفاف و ۱۰۰ کاملاً پوشیده. رنگ زمینه را جدا انتخاب کن.",
    },
    "--header-fixed-backdrop-blur": {
        ...number(0, 40),
        target: "header-behavior",
        help: "میزان محوشدن محتوای پشت منوی ثابت. مقدار ۰ این اثر را حذف می‌کند.",
    },
    "--header-fixed-shadow": {
        type: "text",
        validate: "shadow",
        example: "0 6px 24px #0f172b29",
        target: "header-behavior",
        help: "سایهٔ زیر منوی ثابت. برای حذف سایه، none وارد کن.",
    },
    "font-size": number(6, 160),
    "line-height": number(0.8, 4, ""),
    "font-weight": choice("300", "400", "500", "600", "700", "800", "900"),
    "text-align": choice("right", "justify", "center", "left", "start"),
    "text-align-last": choice("auto", "right", "center", "left"),
    direction: choice("rtl", "ltr"),
    "min-height": number(0, 2400),
    height: number(0, 2400, "px", ["auto"]),
    "max-height": number(0, 2400, "px", ["none"]),
    width: number(0, 100, "%", ["auto", "fit-content", "max-content", "min-content"]),
    "max-width": number(0, 2400, "px", ["none"]),
    "padding-top": number(0, 400),
    "padding-right": number(0, 400),
    "padding-bottom": number(0, 400),
    "padding-left": number(0, 400),
    "margin-top": number(-500, 500),
    "margin-bottom": number(-500, 500),
    "margin-right": number(-500, 500, "px", ["auto"]),
    "margin-left": number(-500, 500, "px", ["auto"]),
    gap: number(0, 240),
    "border-radius": number(0, 200),
    "grid-template-columns": { ...number(1, 12, "columns"), text: "tracks" },
    display: choice(
        "block",
        "inline",
        "inline-block",
        "flex",
        "inline-flex",
        "grid",
        "inline-grid",
        "contents",
        "table",
        "table-row",
        "table-cell",
        "list-item",
        "none",
    ),
    "row-gap": number(0, 240),
    "column-gap": number(0, 240),
    "flex-wrap": choice("nowrap", "wrap", "wrap-reverse"),
    "justify-self": choice("start", "end", "center", "stretch"),
    "align-self": choice("auto", "flex-start", "flex-end", "center", "stretch"),
    "border-width": number(0, 20),
    "border-color": { type: "color" },
    "border-style": choice("none", "solid", "dashed", "dotted"),
    "letter-spacing": number(-10, 30),
    "word-spacing": number(-10, 60),
    "white-space": choice("normal", "nowrap", "pre-wrap"),
    overflow: choice("visible", "hidden", "clip", "auto", "scroll"),
    "overflow-wrap": choice("normal", "break-word", "anywhere"),
    "align-items": choice("flex-start", "flex-end", "start", "end", "center", "stretch", "baseline"),
    "justify-content": choice(
        "flex-start",
        "flex-end",
        "start",
        "end",
        "center",
        "space-between",
        "space-around",
        "space-evenly",
    ),
    "flex-direction": choice("row", "row-reverse", "column", "column-reverse"),
    "object-fit": choice("contain", "cover", "fill", "scale-down"),
    "object-position": { type: "text", validate: "object-position", example: "50% 50%" },
    "image-source": {
        type: "image",
        virtual: true,
        target: "about-image",
        example: "/assets/images/about/about-team.svg",
    },
    transform: choice("none"),
    opacity: number(0, 1, ""),
    color: { type: "color" },
    "background-color": { type: "color" },
    // Virtual control: the compiler emits all declarations required for a clamp.
    "description-lines": number(0, 10, "lines"),

    // Values are validated before preview, export and local file writes.
    "min-width": number(0, 7680),
    "flex-basis": number(0, 7680, "px", ["auto", "content"]),
    "flex-grow": number(0, 20, ""),
    "flex-shrink": number(0, 20, ""),
    order: { ...number(-100, 100, ""), integer: true },
    "grid-template-rows": { type: "text", validate: "tracks", example: "auto 1fr auto" },
    "grid-auto-flow": choice("row", "column", "row dense", "column dense"),
    "grid-column": { type: "text", validate: "grid-line", example: "1 / -1" },
    "grid-row": { type: "text", validate: "grid-line", example: "span 2" },
    "align-content": choice(
        "normal",
        "start",
        "end",
        "center",
        "stretch",
        "space-between",
        "space-around",
        "space-evenly",
    ),
    "justify-items": choice("start", "end", "center", "stretch"),
    position: choice("static", "relative", "absolute", "sticky", "fixed"),
    top: number(-7680, 7680, "px", ["auto"]),
    right: number(-7680, 7680, "px", ["auto"]),
    bottom: number(-7680, 7680, "px", ["auto"]),
    left: number(-7680, 7680, "px", ["auto"]),
    "z-index": { ...number(-100, 2147483646, "", ["auto"]), integer: true },
    "box-sizing": choice("border-box", "content-box"),
    "aspect-ratio": { type: "text", validate: "ratio", example: "16 / 9" },
    visibility: choice("visible", "hidden"),
    "overflow-x": choice("visible", "hidden", "clip", "auto", "scroll"),
    "overflow-y": choice("visible", "hidden", "clip", "auto", "scroll"),
    "border-top-left-radius": number(0, 400),
    "border-top-right-radius": number(0, 400),
    "border-bottom-left-radius": number(0, 400),
    "border-bottom-right-radius": number(0, 400),
    "box-shadow": { type: "text", validate: "shadow", example: "0 8px 24px #0f172b20" },
    "text-decoration-line": choice("none", "underline", "overline", "line-through"),
    "text-decoration-color": { type: "color" },
    "text-decoration-thickness": number(0, 20),
    "text-underline-offset": number(0, 40),
    "text-overflow": choice("clip", "ellipsis"),
    "font-style": choice("normal", "italic"),
    "list-style-type": choice("none", "disc", "circle", "square", "decimal"),
    cursor: choice("auto", "default", "pointer", "text", "grab", "not-allowed"),
    "pointer-events": choice("auto", "none"),
    "transition-duration": number(0, 10000, "ms"),
    "transition-timing-function": choice("ease", "ease-in", "ease-out", "ease-in-out", "linear"),
    rotate: number(-360, 360, "deg"),
    scale: number(0, 10, "", ["none"]),
    "translate-x": { ...number(-7680, 7680), virtual: true },
    "translate-y": { ...number(-7680, 7680), virtual: true },
    // Scoped on body[data-page]; edit active tokens at any responsive range.
    "--color-brand-navy": { type: "color", theme: true },
    "--color-brand-blue": { type: "color", theme: true },
    "--color-brand-orange": { type: "color", theme: true },
    "--color-page-bg": { type: "color", theme: true },
    "--site-gutter": { ...number(0, 300), theme: true },
    "--site-layout-max-width": { ...number(1180, 3840), theme: true },
    "--card-radius": { ...number(0, 200), theme: true },
    "--hero-title-font-size": { ...number(6, 160), theme: true },
    "--hero-description-font-size": { ...number(6, 160), theme: true },
    "--card-title-font-size": { ...number(6, 160), theme: true },
    "--card-description-font-size": { ...number(6, 160), theme: true },
    "--card-media-tag-font-size": { ...number(6, 160), theme: true },
    "--card-meta-tag-font-size": { ...number(6, 160), theme: true },
    "--card-link-font-size": { ...number(6, 160), theme: true },
};
